const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'js/translations.js');

const original = require(filePath);
const { translations, cityDetails, carouselData } = original;
const en = translations.en;
const langs = ['zh-CN','ja','ko','ru','fr','de','es'];

let filledCount = 0;

langs.forEach(lang => {
  const langSection = translations[lang];
  Object.keys(en).forEach(key => {
    const val = langSection[key];
    // If missing, placeholder (equals key), or empty, fill with English
    if (!langSection.hasOwnProperty(key) || val === key || val === '' || val === null) {
      langSection[key] = en[key];
      filledCount++;
    }
  });
});

console.log(`Filled ${filledCount} missing/placeholder/empty entries with English.`);

// Write back
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
output.push(`const translations = ${JSON.stringify(translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);