const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'js/translations.js');
const data = require(filePath);

const langs = ['en','zh-CN','ja','ko','ru','fr','de','es'];
const en = data.translations.en;

let totalAdded = 0;
let totalFilledEmpty = 0;

langs.forEach(lang => {
  if (lang === 'en') return;
  const langSection = data.translations[lang];
  Object.keys(en).forEach(key => {
    if (!langSection.hasOwnProperty(key)) {
      langSection[key] = en[key];
      totalAdded++;
      console.log(`Added missing key '${key}' to ${lang}`);
    } else if (langSection[key] === '' || langSection[key] === null) {
      langSection[key] = en[key];
      totalFilledEmpty++;
      console.log(`Filled empty key '${key}' in ${lang}`);
    }
  });
});

console.log(`Total missing keys added: ${totalAdded}`);
console.log(`Total empty keys filled: ${totalFilledEmpty}`);

// Write back
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
// We need to rebuild the file in the original format.
// Since we don't have the original formatting, we'll just stringify carefully.
// However, the original file has a specific structure: it defines translations and cityDetails and carouselData.
// Let's instead write the whole object as the original did.
// We'll read the original to get the structure? Simpler: we can just overwrite with our modified data.
// But we must keep the same format: 
// const translations = { ... };
// const cityDetails = { ... };
// module.exports = { translations, cityDetails, carouselData };
// We'll extract the other properties from the original require.
const original = require(filePath);
const { cityDetails, carouselData } = original;
output.push(`const translations = ${JSON.stringify(data.translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);
