const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'js/translations.js');
const rootDir = path.join(__dirname, '.');

// Read the translations file
const original = require(filePath);
let { translations, cityDetails, carouselData } = original;

// Function to strip HTML tags
function stripTags(html) {
  return html.replace(/<[^>]*>/g, '');
}

// We'll collect key->text from HTML files
const keyToText = new Map();

// Read all HTML files in root
const files = fs.readdirSync(rootDir);
for (const file of files) {
  if (file.endsWith('.html')) {
    const content = fs.readFileSync(path.join(rootDir, file), 'utf8');
    // We'll use a regex to find all elements with data-lang-key and capture the innerHTML.
    // This regex is not perfect but should work for our case: it matches the whole element and captures the content between the opening and closing tag.
    // We'll use: <[^>]*data-lang-key="([^"])"[^>]*>([\s\S]*?)</[^>]*>
    // But note: the closing tag might be different (e.g., </p> vs </div>). We'll use a lazy dot and then look for the first closing tag that starts with '</'.
    // We'll instead do a simpler approach: we'll split by 'data-lang-key="' and then process each part.
    // Let's do a more robust method: we'll iterate over the string and use a state machine? Given time, we'll use a regex that may fail for nested tags but hope that the innerHTML does not contain other elements with the same key.
    const regex = /<[^>]*data-lang-key="([^"])"[^>]*>([\s\S]*?)</g;
    let match;
    while ((match = regex.exec(content)) !== null) {
      const key = match[1];
      let innerHTML = match[2];
      // Strip HTML tags
      let text = stripTags(innerHTML);
      // Trim whitespace
      text = text.trim();
      if (text !== '') {
        // If we already have a text for this key, we'll keep the first one.
        if (!keyToText.has(key)) {
          keyToText.set(key, text);
        }
      }
    }
  }
}

console.log(`Found ${keyToText.size} unique key-text pairs from HTML files.`);

// Now update translations.en for keys that are placeholders (value equals key) or empty
let updatedCount = 0;
for (const [key, text] of keyToText.entries()) {
  if (translations.en.hasOwnProperty(key)) {
    const val = translations.en[key];
    if (val === key || val === '') {
      translations.en[key] = text;
      updatedCount++;
      console.log(`Updated en.${key}: ${text.substring(0, 50)}...`);
    }
  } else {
    // Key not in EN section, we should add it? But the task is about fixing existing keys.
    // We'll skip for now.
  }
}

console.log(`Updated ${updatedCount} placeholder/empty keys in en with HTML text.`);

// Now fix placeholders in other languages where EN value is not a placeholder (i.e., EN value is actual text)
let fixedCount = 0;
const langs = ['zh-CN','ja','ko','ru','fr','de','es'];
langs.forEach(lang => {
  const langSection = translations[lang];
  Object.keys(translations.en).forEach(key => {
    const langVal = langSection[key];
    const enVal = translations.en[key];
    // If the language value is a placeholder (equals the key) and the English value is not a placeholder (not equal to the key) and not empty
    if (langVal === key && enVal !== key && enVal !== '') {
      langSection[key] = enVal;
      fixedCount++;
    }
  });
});

console.log(`Fixed ${fixedCount} placeholders in non-EN sections where EN value is actual text.`);

// Write back
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
output.push(`const translations = ${JSON.stringify(translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);