const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'js/translations.js');

const original = require(filePath);
const { translations, cityDetails, carouselData } = original;
const en = translations.en;
const langs = ['zh-CN','ja','ko','ru','fr','de','es'];

let fixedCount = 0;

// Fix placeholders in non-EN sections where EN value is not a placeholder
langs.forEach(lang => {
  const langSection = translations[lang];
  Object.keys(en).forEach(key => {
    const langVal = langSection[key];
    const enVal = en[key];
    // If the language value is a placeholder (equals the key) and the English value is not a placeholder (not equal to the key)
    if (langVal === key && enVal !== key) {
      langSection[key] = enVal;
      fixedCount++;
    }
  });
});

console.log(`Fixed ${fixedCount} placeholders in non-EN sections where EN value is actual text.`);

// Write back
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
output.push(`const translations = ${JSON.stringify(translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);