const fs = require('fs');
const path = require('path');

// We'll process only the root HTML files for now.
const rootDir = path.join(__dirname, '.');

// Read the translations file
const filePath = path.join(__dirname, 'js/translations.js');
const original = require(filePath);
let { translations, cityDetails, carouselData } = original;

// Function to strip HTML tags
function stripTags(html) {
  return html.replace(/<[^>]*>/g, '');
}

// We'll collect key->text from HTML files
const keyToText = new Map();

// Read all HTML files in root
const files = fs.readdirSync(rootDir);
for (const file of files) {
  if (file.endsWith('.html')) {
    const content = fs.readFileSync(path.join(rootDir, file), 'utf8');
    // Find all occurrences of data-lang-key="key"
    // We'll use a regex that matches the attribute and then capture until the next >, then we need to find the closing tag.
    // Instead, we can do: match the whole element with a regex that is not perfect but works for most cases.
    // We'll look for: <[^>]*data-lang-key="([^"])"[^>]*>([\s\S]*?)</[^>]*>
    // But note: the closing tag might be different (e.g., </p> vs </div>). We'll use a lazy dot and then look for the first closing tag that matches the opening tag? Too complex.
    // Given the time, we'll assume that the element is self-contained on one line and does not contain nested elements with the same key.
    // We'll use a regex that matches the line and captures the content between > and <.
    const lines = content.split('\n');
    for (const line of lines) {
      // Match: data-lang-key="key" ... > content <
      const match = line.match(/data-lang-key="([^"])"[^>]*>([^<]*)</);
      if (match) {
        const key = match[1];
        let text = match[2];
        // If the text is empty, maybe the tag has inner tags and the text is on another line.
        // We'll skip for now.
        if (text.trim() !== '') {
          keyToText.set(key, text);
        }
      }
    }
  }
}

console.log(`Found ${keyToText.size} key-text pairs from HTML files (simple line-based).`);

// Now update translations.en for keys that are placeholders (value equals key)
let updatedCount = 0;
for (const [key, text] of keyToText.entries()) {
  if (translations.en.hasOwnProperty(key) && translations.en[key] === key) {
    translations.en[key] = text;
    updatedCount++;
    console.log(`Updated en.${key}: ${text.substring(0, 50)}...`);
  }
}

console.log(`Updated ${updatedCount} placeholder keys in en with HTML text.`);

// Now fix placeholders in other languages where EN value is not a placeholder
let fixedCount = 0;
const langs = ['zh-CN','ja','ko','ru','fr','de','es'];
langs.forEach(lang => {
  const langSection = translations[lang];
  Object.keys(translations.en).forEach(key => {
    const langVal = langSection[key];
    const enVal = translations.en[key];
    if (langVal === key && enVal !== key) {
      langSection[key] = enVal;
      fixedCount++;
    }
  });
});

console.log(`Fixed ${fixedCount} placeholders in non-EN sections.`);

// Write back
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
output.push(`const translations = ${JSON.stringify(translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);