const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'js/translations.js');
const data = require(filePath);
const en = data.translations.en;
const langs = ['zh-CN','ja','ko','ru','fr','de','es'];

let totalFixed = 0;

langs.forEach(lang => {
  const langSection = data.translations[lang];
  Object.keys(en).forEach(key => {
    if (langSection[key] === key) {
      langSection[key] = en[key];
      totalFixed++;
      console.log(`Fixed placeholder '${key}' in ${lang} to: "${en[key]}".substring(0, 50)`);
    }
  });
});

console.log(`Total placeholders fixed: ${totalFixed}`);

// Write back
const original = require(filePath);
const { cityDetails, carouselData } = original;
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
output.push(`const translations = ${JSON.stringify(data.translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);