const langData = {
    en: {
        title: "China Travel Guide",
        subtitle: "Explore China: Magnificent Landscapes & Rich Culture",
        nav: ["Famous Attractions", "Local Cuisine", "Travel Tips"],
        scenic: "Famous Attractions",
        scenic1: ["Great Wall", "A world-famous ancient defense project, stretching thousands of miles, and a symbol of China."],
        scenic2: ["The Forbidden City", "Located in Beijing, this imperial palace boasts rich history and culture. It is the largest and best-preserved wooden palace complex in the world."],
        scenic3: ["Guilin Scenery", "Famous for its green mountains, clear waters, unique caves, and beautiful rocks. Known as 'the best landscape under heaven'."],
        scenic4: ["West Lake", "Located in Hangzhou, renowned for its beautiful scenery and rich cultural heritage."],
        food: "Local Cuisine",
        food1: ["Peking Duck", "Crispy outside and tender inside, Peking Duck is one of Beijing's most iconic dishes."],
        food2: ["Chongqing Hotpot", "Spicy and flavorful with a variety of ingredients, a signature food experience in southern China."],
        food3: ["Shanghai Soup Dumplings", "Thin skin, juicy filling, a traditional delicacy from the Jiangnan region."],
        food4: ["Lanzhou Noodles", "Chewy noodles in a savory broth, a representative noodle dish from northwest China."],
        info: "Travel Tips",
        info1: "<strong>Best Time to Visit:</strong> Spring and autumn offer pleasant weather for most regions.",
        info2: "<strong>Transportation:</strong> China has a well-developed high-speed rail and air network, making intercity travel convenient.",
        info3: "<strong>Visa:</strong> Most foreign visitors need to apply for a Chinese visa in advance.",
        info4: "<strong>Currency:</strong> Renminbi (CNY). Mobile payments (Alipay, WeChat Pay) are widely used.",
        info5: "<strong>Language:</strong> Mandarin is the official language. Major attractions have English signs.",
        footer: "&copy; 2025 China Travel Guide | Powered by AI Assistant"
    },
    fr: {
        title: "Guide de Voyage en Chine",
        subtitle: "Explorez la Chine : paysages magnifiques et culture riche",
        nav: ["Sites célèbres", "Cuisine locale", "Conseils pratiques"],
        scenic: "Sites célèbres",
        scenic1: ["Grande Muraille", "Un projet de défense antique mondialement célèbre, s'étendant sur des milliers de kilomètres, symbole de la Chine."],
        scenic2: ["Cité Interdite", "Situé à Pékin, ce palais impérial possède une histoire et une culture riches. C'est le plus grand complexe de palais en bois au monde, parfaitement préservé."],
        scenic3: ["Paysages de Guilin", "Célèbre pour ses montagnes verdoyantes, ses eaux claires, ses grottes uniques et ses rochers magnifiques. Surnommé 'le plus beau paysage sous le ciel'."],
        scenic4: ["Lac de l'Ouest", "Situé à Hangzhou, réputé pour sa beauté naturelle et son riche patrimoine culturel."],
        food: "Cuisine locale",
        food1: ["Canard laqué de Pékin", "Peau croustillante et chair tendre, le canard laqué est l'un des plats les plus emblématiques de Pékin."],
        food2: ["Fondue de Chongqing", "Épicée et savoureuse avec une grande variété d'ingrédients, une expérience culinaire typique du sud de la Chine."],
        food3: ["Raviolis de Shanghai", "Peau fine, farce juteuse, une spécialité traditionnelle de la région du Jiangnan."],
        food4: ["Nouilles de Lanzhou", "Nouilles fermes dans un bouillon savoureux, un plat représentatif du nord-ouest de la Chine."],
        info: "Conseils pratiques",
        info1: "<strong>Meilleure période :</strong> Le printemps et l'automne offrent un climat agréable dans la plupart des régions.",
        info2: "<strong>Transports :</strong> La Chine dispose d'un réseau ferroviaire à grande vitesse et aérien très développé, facilitant les déplacements interurbains.",
        info3: "<strong>Visa :</strong> La plupart des visiteurs étrangers doivent demander un visa chinois à l'avance.",
        info4: "<strong>Monnaie :</strong> Renminbi (CNY). Les paiements mobiles (Alipay, WeChat Pay) sont très répandus.",
        info5: "<strong>Langue :</strong> Le mandarin est la langue officielle. Les principaux sites touristiques disposent de panneaux en anglais.",
        footer: "&copy; 2025 Guide de Voyage en Chine | Propulsé par AI Assistant"
    },
    de: {
        title: "China Reiseführer",
        subtitle: "Entdecken Sie China: Prächtige Landschaften & reiche Kultur",
        nav: ["Berühmte Sehenswürdigkeiten", "Lokale Küche", "Reisetipps"],
        scenic: "Berühmte Sehenswürdigkeiten",
        scenic1: ["Chinesische Mauer", "Ein weltberühmtes antikes Verteidigungsbauwerk, das sich über Tausende von Kilometern erstreckt und ein Symbol Chinas ist."],
        scenic2: ["Verbotene Stadt", "In Peking gelegen, bietet dieser Kaiserpalast eine reiche Geschichte und Kultur. Es ist der größte und am besten erhaltene Holzpalastkomplex der Welt."],
        scenic3: ["Guilin Landschaft", "Berühmt für grüne Berge, klares Wasser, einzigartige Höhlen und schöne Felsen. Bekannt als 'die schönste Landschaft unter dem Himmel'."],
        scenic4: ["Westsee", "In Hangzhou gelegen, bekannt für seine schöne Landschaft und sein reiches kulturelles Erbe."],
        food: "Lokale Küche",
        food1: ["Peking-Ente", "Knusprig außen und zart innen, eine der bekanntesten Spezialitäten Pekings."],
        food2: ["Chongqing Hotpot", "Würzig und aromatisch mit einer Vielzahl von Zutaten, ein typisches kulinarisches Erlebnis in Südchina."],
        food3: ["Shanghai Suppenknödel", "Dünner Teig, saftige Füllung, eine traditionelle Delikatesse aus der Jiangnan-Region."],
        food4: ["Lanzhou Nudeln", "Feste Nudeln in einer herzhaften Brühe, ein repräsentatives Nudelgericht aus Nordwestchina."],
        info: "Reisetipps",
        info1: "<strong>Beste Reisezeit:</strong> Frühling und Herbst bieten angenehmes Wetter in den meisten Regionen.",
        info2: "<strong>Verkehr:</strong> China verfügt über ein gut ausgebautes Hochgeschwindigkeitsbahn- und Flugnetz, das Reisen zwischen Städten erleichtert.",
        info3: "<strong>Visum:</strong> Die meisten ausländischen Besucher müssen im Voraus ein chinesisches Visum beantragen.",
        info4: "<strong>Währung:</strong> Renminbi (CNY). Mobile Zahlungen (Alipay, WeChat Pay) sind weit verbreitet.",
        info5: "<strong>Sprache:</strong> Mandarin ist die Amtssprache. Wichtige Sehenswürdigkeiten sind auf Englisch ausgeschildert.",
        footer: "&copy; 2025 China Reiseführer | Bereitgestellt von AI Assistant"
    },
    es: {
        title: "Guía de Viaje de China",
        subtitle: "Explora China: Paisajes magníficos y cultura rica",
        nav: ["Atracciones famosas", "Gastronomía local", "Consejos de viaje"],
        scenic: "Atracciones famosas",
        scenic1: ["Gran Muralla", "Un famoso proyecto de defensa antiguo, que se extiende por miles de kilómetros y es un símbolo de China."],
        scenic2: ["Ciudad Prohibida", "Ubicado en Pekín, este palacio imperial cuenta con una rica historia y cultura. Es el complejo de palacios de madera más grande y mejor conservado del mundo."],
        scenic3: ["Paisaje de Guilin", "Famoso por sus montañas verdes, aguas claras, cuevas únicas y hermosas rocas. Conocido como 'el mejor paisaje bajo el cielo'."],
        scenic4: ["Lago del Oeste", "Ubicado en Hangzhou, famoso por su hermoso paisaje y su rico patrimonio cultural."],
        food: "Gastronomía local",
        food1: ["Pato Pekín", "Crujiente por fuera y tierno por dentro, el Pato Pekín es uno de los platos más emblemáticos de Pekín."],
        food2: ["Hotpot de Chongqing", "Picante y sabroso con una variedad de ingredientes, una experiencia culinaria típica del sur de China."],
        food3: ["Dumplings de Shanghai", "Piel fina, relleno jugoso, una delicia tradicional de la región de Jiangnan."],
        food4: ["Fideos de Lanzhou", "Fideos firmes en un caldo sabroso, un plato representativo del noroeste de China."],
        info: "Consejos de viaje",
        info1: "<strong>Mejor época para visitar:</strong> La primavera y el otoño ofrecen un clima agradable en la mayoría de las regiones.",
        info2: "<strong>Transporte:</strong> China cuenta con una red de trenes de alta velocidad y vuelos muy desarrollada, lo que facilita los viajes entre ciudades.",
        info3: "<strong>Visado:</strong> La mayoría de los visitantes extranjeros deben solicitar un visado chino con antelación.",
        info4: "<strong>Moneda:</strong> Renminbi (CNY). Los pagos móviles (Alipay, WeChat Pay) están muy extendidos.",
        info5: "<strong>Idioma:</strong> El mandarín es el idioma oficial. Las principales atracciones tienen señalización en inglés.",
        footer: "&copy; 2025 Guía de Viaje de China | Desarrollado por AI Assistant"
    },
    ja: {
        title: "中国旅行ガイド",
        subtitle: "中国を探検しよう：壮大な景色と豊かな文化",
        nav: ["有名な観光地", "ご当地グルメ", "旅行のヒント"],
        scenic: "有名な観光地",
        scenic1: ["万里の長城", "世界的に有名な古代の防御施設で、数千キロにわたり中国の象徴です。"],
        scenic2: ["故宮（紫禁城）", "北京にある皇帝の宮殿で、豊かな歴史と文化を誇ります。世界最大かつ最も保存状態の良い木造宮殿建築です。"],
        scenic3: ["桂林の景観", "緑の山々、澄んだ水、ユニークな洞窟、美しい岩で有名。「山水は天下一」と称されています。"],
        scenic4: ["西湖", "杭州にあり、美しい景色と豊かな文化遺産で有名です。"],
        food: "ご当地グルメ",
        food1: ["北京ダック", "外はパリッと中はジューシーで、北京を代表する料理の一つです。"],
        food2: ["重慶火鍋", "辛くて風味豊か、様々な具材が楽しめる南中国の名物料理です。"],
        food3: ["上海小籠包", "薄皮でジューシーなスープ入り、江南地方の伝統的な点心です。"],
        food4: ["蘭州ラーメン", "コシのある麺と旨味たっぷりのスープが特徴の西北地方の代表的な麺料理です。"],
        info: "旅行のヒント",
        info1: "<strong>ベストシーズン：</strong> 春と秋は多くの地域で快適な気候です。",
        info2: "<strong>交通：</strong> 中国は高速鉄道と航空網が発達しており、都市間の移動が便利です。",
        info3: "<strong>ビザ：</strong> 多くの外国人旅行者は事前に中国ビザの取得が必要です。",
        info4: "<strong>通貨：</strong> 人民元（CNY）。モバイル決済（Alipay、WeChat Pay）が広く普及しています。",
        info5: "<strong>言語：</strong> 公用語は中国語（普通話）で、主要観光地には英語表記もあります。",
        footer: "&copy; 2025 中国旅行ガイド | AIアシスタント提供"
    },
    ko: {
        title: "중국 여행 가이드",
        subtitle: "중국 탐험: 웅장한 풍경과 풍부한 문화",
        nav: ["유명 관광지", "현지 음식", "여행 팁"],
        scenic: "유명 관광지",
        scenic1: ["만리장성", "세계적으로 유명한 고대 방어 시설로, 수천 킬로미터에 걸쳐 중국의 상징입니다."],
        scenic2: ["자금성", "베이징에 위치한 황궁으로, 풍부한 역사와 문화를 자랑합니다. 세계에서 가장 크고 잘 보존된 목조 궁전입니다."],
        scenic3: ["구이린 경치", "푸른 산, 맑은 물, 독특한 동굴, 아름다운 바위로 유명합니다. '천하제일 경치'로 불립니다."],
        scenic4: ["서호", "항저우에 위치하며, 아름다운 경치와 풍부한 문화유산으로 유명합니다."],
        food: "현지 음식",
        food1: ["베이징 오리구이", "겉은 바삭하고 속은 부드러운 베이징을 대표하는 요리입니다."],
        food2: ["충칭 훠궈", "매콤하고 다양한 재료로 남중국의 대표적인 음식 체험입니다."],
        food3: ["상하이 샤오롱바오", "얇은 피와 육즙이 풍부한 강남 지역의 전통 딤섬입니다."],
        food4: ["란저우 라면", "쫄깃한 면과 진한 국물이 특징인 중국 서북부의 대표 면요리입니다."],
        info: "여행 팁",
        info1: "<strong>최적 여행 시기:</strong> 봄과 가을은 대부분 지역에서 쾌적한 날씨를 제공합니다.",
        info2: "<strong>교통:</strong> 중국은 고속철도와 항공망이 잘 발달되어 있어 도시 간 이동이 편리합니다.",
        info3: "<strong>비자:</strong> 대부분의 외국인 방문객은 사전에 중국 비자를 신청해야 합니다.",
        info4: "<strong>통화:</strong> 위안화(CNY). 모바일 결제(알리페이, 위챗페이)가 널리 사용됩니다.",
        info5: "<strong>언어:</strong> 표준 중국어가 공식 언어이며, 주요 관광지에는 영어 표지판이 있습니다.",
        footer: "&copy; 2025 중국 여행 가이드 | AI 어시스턴트 제공"
    },
    th: {
        title: "คู่มือท่องเที่ยวจีน",
        subtitle: "สำรวจจีน: ทิวทัศน์งดงามและวัฒนธรรมอันล้ำค่า",
        nav: ["สถานที่ท่องเที่ยวชื่อดัง", "อาหารท้องถิ่น", "เคล็ดลับการเดินทาง"],
        scenic: "สถานที่ท่องเที่ยวชื่อดัง",
        scenic1: ["กำแพงเมืองจีน", "สิ่งก่อสร้างป้องกันโบราณที่มีชื่อเสียงระดับโลก ยาวหลายพันกิโลเมตร เป็นสัญลักษณ์ของจีน"],
        scenic2: ["พระราชวังต้องห้าม", "ตั้งอยู่ที่ปักกิ่ง เป็นพระราชวังที่มีประวัติศาสตร์และวัฒนธรรมอันยาวนาน ใหญ่และสมบูรณ์ที่สุดในโลก"],
        scenic3: ["ทิวทัศน์กุ้ยหลิน", "มีชื่อเสียงเรื่องภูเขาสีเขียว น้ำใส ถ้ำสวย และโขดหินงาม ได้รับการขนานนามว่า 'ภูมิทัศน์ที่ดีที่สุดใต้ฟ้า'"],
        scenic4: ["ทะเลสาบซีหู", "ตั้งอยู่ที่หางโจว มีทิวทัศน์งดงามและมรดกทางวัฒนธรรมอันล้ำค่า"],
        food: "อาหารท้องถิ่น",
        food1: ["เป็ดปักกิ่ง", "หนังกรอบ เนื้อนุ่ม เป็นอาหารขึ้นชื่อของปักกิ่ง"],
        food2: ["หม้อไฟฉงชิ่ง", "เผ็ดร้อนและมีวัตถุดิบหลากหลาย เป็นประสบการณ์อาหารที่โดดเด่นของจีนตอนใต้"],
        food3: ["เสี่ยวหลงเปาเซี่ยงไฮ้", "แป้งบาง ไส้ฉ่ำ เป็นติ่มซำดั้งเดิมของภูมิภาคเจียงหนาน"],
        food4: ["บะหมี่หลานโจว", "เส้นเหนียวนุ่ม น้ำซุปกลมกล่อม เป็นอาหารเส้นขึ้นชื่อของจีนตะวันตกเฉียงเหนือ"],
        info: "เคล็ดลับการเดินทาง",
        info1: "<strong>ช่วงเวลาที่ดีที่สุด:</strong> ฤดูใบไม้ผลิและฤดูใบไม้ร่วงอากาศดี เหมาะกับการท่องเที่ยวส่วนใหญ่",
        info2: "<strong>การเดินทาง:</strong> จีนมีเครือข่ายรถไฟความเร็วสูงและสายการบินที่ทันสมัย เดินทางระหว่างเมืองสะดวก",
        info3: "<strong>วีซ่า:</strong> นักท่องเที่ยวต่างชาติโดยส่วนใหญ่ต้องขอวีซ่าจีนล่วงหน้า",
        info4: "<strong>สกุลเงิน:</strong> หยวน (CNY) การชำระเงินผ่านมือถือ (Alipay, WeChat Pay) เป็นที่นิยมมาก",
        info5: "<strong>ภาษา:</strong> ภาษาจีนกลางเป็นภาษาราชการ สถานที่ท่องเที่ยวหลักมีป้ายภาษาอังกฤษ",
        footer: "&copy; 2025 คู่มือท่องเที่ยวจีน | จัดทำโดย AI Assistant"
    }
};
