const langData = {
    en: {
        title: "China Travel Guide",
        subtitle: "Explore China: Magnificent Landscapes & Rich Culture",
        nav: ["Famous Attractions", "Local Cuisine", "Travel Tips"],
        scenic: "Famous Attractions",
        scenic1: ["Great Wall", "A world-famous ancient defense project, stretching thousands of miles, and a symbol of China."],
        scenic2: ["The Forbidden City", "Located in Beijing, this imperial palace boasts rich history and culture. It is the largest and best-preserved wooden palace complex in the world."],
        scenic3: ["Guilin Scenery", "Famous for its green mountains, clear waters, unique caves, and beautiful rocks. Known as 'the best landscape under heaven'."],
        scenic4: ["West Lake", "Located in Hangzhou, renowned for its beautiful scenery and rich cultural heritage."],
        food: "Local Cuisine",
        food1: ["Peking Duck", "Crispy outside and tender inside, Peking Duck is one of Beijing's most iconic dishes."],
        food2: ["Chongqing Hotpot", "Spicy and flavorful with a variety of ingredients, a signature food experience in southern China."],
        food3: ["Shanghai Soup Dumplings", "Thin skin, juicy filling, a traditional delicacy from the Jiangnan region."],
        food4: ["Lanzhou Noodles", "Chewy noodles in a savory broth, a representative noodle dish from northwest China."],
        info: "Travel Tips",
        info1: "<strong>Best Time to Visit:</strong> Spring and autumn offer pleasant weather for most regions.",
        info2: "<strong>Transportation:</strong> China has a well-developed high-speed rail and air network, making intercity travel convenient.",
        info3: "<strong>Visa:</strong> Most foreign visitors need to apply for a Chinese visa in advance.",
        info4: "<strong>Currency:</strong> Renminbi (CNY). Mobile payments (Alipay, WeChat Pay) are widely used.",
        info5: "<strong>Language:</strong> Mandarin is the official language. Major attractions have English signs.",
        footer: "&copy; 2025 China Travel Guide | Powered by AI Assistant"
    },
    fr: {
        title: "Guide de Voyage en Chine",
        subtitle: "Explorez la Chine : paysages magnifiques et culture riche",
        nav: ["Sites célèbres", "Cuisine locale", "Conseils pratiques"],
        scenic: "Sites célèbres",
        scenic1: ["Grande Muraille", "Un projet de défense antique mondialement célèbre, s'étendant sur des milliers de kilomètres, symbole de la Chine."],
        scenic2: ["Cité Interdite", "Situé à Pékin, ce palais impérial possède une histoire et une culture riches. C'est le plus grand complexe de palais en bois au monde, parfaitement préservé."],
        scenic3: ["Paysages de Guilin", "Célèbre pour ses montagnes verdoyantes, ses eaux claires, ses grottes uniques et ses rochers magnifiques. Surnommé 'le plus beau paysage sous le ciel'."],
        scenic4: ["Lac de l'Ouest", "Situé à Hangzhou, réputé pour sa beauté naturelle et son riche patrimoine culturel."],
        food: "Cuisine locale",
        food1: ["Canard laqué de Pékin", "Peau croustillante et chair tendre, le canard laqué est l'un des plats les plus emblématiques de Pékin."],
        food2: ["Fondue de Chongqing", "Épicée et savoureuse avec une grande variété d'ingrédients, une expérience culinaire typique du sud de la Chine."],
        food3: ["Raviolis de Shanghai", "Peau fine, farce juteuse, une spécialité traditionnelle de la région du Jiangnan."],
        food4: ["Nouilles de Lanzhou", "Nouilles fermes dans un bouillon savoureux, un plat représentatif du nord-ouest de la Chine."],
        info: "Conseils pratiques",
        info1: "<strong>Meilleure période :</strong> Le printemps et l'automne offrent un climat agréable dans la plupart des régions.",
        info2: "<strong>Transports :</strong> La Chine dispose d'un réseau ferroviaire à grande vitesse et aérien très développé, facilitant les déplacements interurbains.",
        info3: "<strong>Visa :</strong> La plupart des visiteurs étrangers doivent demander un visa chinois à l'avance.",
        info4: "<strong>Monnaie :</strong> Renminbi (CNY). Les paiements mobiles (Alipay, WeChat Pay) sont très répandus.",
        info5: "<strong>Langue :</strong> Le mandarin est la langue officielle. Les principaux sites touristiques disposent de panneaux en anglais.",
        footer: "&copy; 2025 Guide de Voyage en Chine | Propulsé par AI Assistant"
    },
    de: {
        title: "China Reiseführer",
        subtitle: "Entdecken Sie China: Prächtige Landschaften & reiche Kultur",
        nav: ["Berühmte Sehenswürdigkeiten", "Lokale Küche", "Reisetipps"],
        scenic: "Berühmte Sehenswürdigkeiten",
        scenic1: ["Chinesische Mauer", "Ein weltberühmtes antikes Verteidigungsbauwerk, das sich über Tausende von Kilometern erstreckt und ein Symbol Chinas ist."],
        scenic2: ["Verbotene Stadt", "In Peking gelegen, bietet dieser Kaiserpalast eine reiche Geschichte und Kultur. Es ist der größte und am besten erhaltene Holzpalastkomplex der Welt."],
        scenic3: ["Guilin Landschaft", "Berühmt für grüne Berge, klares Wasser, einzigartige Höhlen und schöne Felsen. Bekannt als 'die schönste Landschaft unter dem Himmel'."],
        scenic4: ["Westsee", "In Hangzhou gelegen, bekannt für seine schöne Landschaft und sein reiches kulturelles Erbe."],
        food: "Lokale Küche",
        food1: ["Peking-Ente", "Knusprig außen und zart innen, eine der bekanntesten Spezialitäten Pekings."],
        food2: ["Chongqing Hotpot", "Würzig und aromatisch mit einer Vielzahl von Zutaten, ein typisches kulinarisches Erlebnis in Südchina."],
        food3: ["Shanghai Suppenknödel", "Dünner Teig, saftige Füllung, eine traditionelle Delikatesse aus der Jiangnan-Region."],
        food4: ["Lanzhou Nudeln", "Feste Nudeln in einer herzhaften Brühe, ein repräsentatives Nudelgericht aus Nordwestchina."],
        info: "Reisetipps",
        info1: "<strong>Beste Reisezeit:</strong> Frühling und Herbst bieten angenehmes Wetter in den meisten Regionen.",
        info2: "<strong>Verkehr:</strong> China verfügt über ein gut ausgebautes Hochgeschwindigkeitsbahn- und Flugnetz, das Reisen zwischen Städten erleichtert.",
        info3: "<strong>Visum:</strong> Die meisten ausländischen Besucher müssen im Voraus ein chinesisches Visum beantragen.",
        info4: "<strong>Währung:</strong> Renminbi (CNY). Mobile Zahlungen (Alipay, WeChat Pay) sind weit verbreitet.",
        info5: "<strong>Sprache:</strong> Mandarin ist die Amtssprache. Wichtige Sehenswürdigkeiten sind auf Englisch ausgeschildert.",
        footer: "&copy; 2025 China Reiseführer | Bereitgestellt von AI Assistant"
    },
    es: {
        title: "Guía de Viaje de China",
        subtitle: "Explora China: Paisajes magníficos y cultura rica",
        nav: ["Atracciones famosas", "Gastronomía local", "Consejos de viaje"],
        scenic: "Atracciones famosas",
        scenic1: ["Gran Muralla", "Un famoso proyecto de defensa antiguo, que se extiende por miles de kilómetros y es un símbolo de China."],
        scenic2: ["Ciudad Prohibida", "Ubicado en Pekín, este palacio imperial cuenta con una rica historia y cultura. Es el complejo de palacios de madera más grande y mejor conservado del mundo."],
        scenic3: ["Paisaje de Guilin", "Famoso por sus montañas verdes, aguas claras, cuevas únicas y hermosas rocas. Conocido como 'el mejor paisaje bajo el cielo'."],
        scenic4: ["Lago del Oeste", "Ubicado en Hangzhou, famoso por su hermoso paisaje y su rico patrimonio cultural."],
        food: "Gastronomía local",
        food1: ["Pato Pekín", "Crujiente por fuera y tierno por dentro, el Pato Pekín es uno de los platos más emblemáticos de Pekín."],
        food2: ["Hotpot de Chongqing", "Picante y sabroso con una variedad de ingredientes, una experiencia culinaria típica del sur de China."],
        food3: ["Dumplings de Shanghai", "Piel fina, relleno jugoso, una delicia tradicional de la región de Jiangnan."],
        food4: ["Fideos de Lanzhou", "Fideos firmes en un caldo sabroso, un plato representativo del noroeste de China."],
        info: "Consejos de viaje",
        info1: "<strong>Mejor época para visitar:</strong> La primavera y el otoño ofrecen un clima agradable en la mayoría de las regiones.",
        info2: "<strong>Transporte:</strong> China cuenta con una red de trenes de alta velocidad y vuelos muy desarrollada, lo que facilita los viajes entre ciudades.",
        info3: "<strong>Visado:</strong> La mayoría de los visitantes extranjeros deben solicitar un visado chino con antelación.",
        info4: "<strong>Moneda:</strong> Renminbi (CNY). Los pagos móviles (Alipay, WeChat Pay) están muy extendidos.",
        info5: "<strong>Idioma:</strong> El mandarín es el idioma oficial. Las principales atracciones tienen señalización en inglés.",
        footer: "&copy; 2025 Guía de Viaje de China | Desarrollado por AI Assistant"
    },
    it: {
        title: "Guida di Viaggio in Cina",
        subtitle: "Esplora la Cina: paesaggi magnifici e cultura ricca",
        nav: ["Attrazioni famose", "Cucina locale", "Consigli utili"],
        scenic: "Attrazioni famose",
        scenic1: ["Grande Muraglia", "Un famoso progetto di difesa antico, che si estende per migliaia di chilometri ed è un simbolo della Cina."],
        scenic2: ["Città Proibita", "Situato a Pechino, questo palazzo imperiale vanta una ricca storia e cultura. È il più grande e meglio conservato complesso di palazzi in legno al mondo."],
        scenic3: ["Paesaggio di Guilin", "Famoso per le sue montagne verdi, acque limpide, grotte uniche e bellissime rocce. Conosciuto come 'il miglior paesaggio sotto il cielo'."],
        scenic4: ["Lago dell'Ovest", "Situato a Hangzhou, rinomato per il suo bellissimo paesaggio e il ricco patrimonio culturale."],
        food: "Cucina locale",
        food1: ["Anatra alla Pechinese", "Croccante fuori e tenera dentro, l'anatra alla pechinese è uno dei piatti più iconici di Pechino."],
        food2: ["Hotpot di Chongqing", "Piccante e saporito con una varietà di ingredienti, un'esperienza culinaria tipica della Cina meridionale."],
        food3: ["Ravioli al vapore di Shanghai", "Pasta sottile, ripieno succoso, una prelibatezza tradizionale della regione del Jiangnan."],
        food4: ["Tagliatelle di Lanzhou", "Tagliatelle sode in un brodo saporito, un piatto rappresentativo della Cina nord-occidentale."],
        info: "Consigli utili",
        info1: "<strong>Miglior periodo per visitare:</strong> Primavera e autunno offrono un clima piacevole nella maggior parte delle regioni.",
        info2: "<strong>Trasporti:</strong> La Cina dispone di una rete ferroviaria ad alta velocità e aerea molto sviluppata, che rende comodi gli spostamenti tra le città.",
        info3: "<strong>Visto:</strong> La maggior parte dei visitatori stranieri deve richiedere un visto cinese in anticipo.",
        info4: "<strong>Valuta:</strong> Renminbi (CNY). I pagamenti mobili (Alipay, WeChat Pay) sono molto diffusi.",
        info5: "<strong>Lingua:</strong> Il mandarino è la lingua ufficiale. Le principali attrazioni hanno segnaletica in inglese.",
        footer: "&copy; 2025 Guida di Viaggio in Cina | Fornito da AI Assistant"
    },
};
