const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'js/translations.js');
const htmlDir = path.join(__dirname, '.'); // root HTML files

// Read translations
const original = require(filePath);
let { translations, cityDetails, carouselData } = original;

// We'll collect key->text from HTML files
const keyToText = new Map();

function extractTextFromHtml(filepath) {
  const content = fs.readFileSync(filepath, 'utf8');
  // Find all elements with data-lang-key
  const regex = /data-lang-key="([^"])"[^>]*>([\s\S]*?)<\//g;
  // Actually, we need to capture the inner content until the closing tag.
  // Simpler: use a regex that matches the whole element and extract innerHTML.
  // But we can do a simpler approach: for each match of data-lang-key="key", we find the next > and then capture until the corresponding closing tag.
  // Given time, we'll just do a simple regex that captures the innerHTML assuming no nested tags with same key? Not reliable.
  // Instead, we'll rely on the fact that the text is often plain text or with simple tags.
  // We'll use a regex that captures everything between > and the next < (but that fails if there are tags inside).
  // Let's do a different approach: we'll just look for the pattern in the file and assume the text is on the same line.
  // Actually, we can look at the line and extract the content between > and <.
  const lines = content.split('\n');
  for (const line of lines) {
    const match = line.match(/data-lang-key="([^"])"[^>]*>([^<]*)</);
    if (match) {
      const key = match[1];
      let text = match[2];
      // If the text is empty, maybe the tag has inner tags.
      // We'll skip for now.
      if (text.trim() !== '') {
        keyToText.set(key, text);
      }
    }
  }
}

// Read all HTML files in root
const files = fs.readdirSync(htmlDir);
for (const file of files) {
  if (file.endsWith('.html')) {
    extractTextFromHtml(path.join(htmlDir, file));
  }
}

console.log(`Found ${keyToText.size} key-text pairs from HTML files.`);

// Now update translations.en for keys that are placeholders (value equals key)
let updatedCount = 0;
for (const [key, text] of keyToText.entries()) {
  if (translations.en.hasOwnProperty(key) && translations.en[key] === key) {
    translations.en[key] = text;
    updatedCount++;
    console.log(`Updated en.${key}: ${text.substring(0, 50)}...`);
  }
}

console.log(`Updated ${updatedCount} placeholder keys in en with HTML text.`);

// Now fix placeholders in other languages where EN value is not a placeholder
let fixedCount = 0;
const langs = ['zh-CN','ja','ko','ru','fr','de','es'];
langs.forEach(lang => {
  const langSection = translations[lang];
  Object.keys(translations.en).forEach(key => {
    const langVal = langSection[key];
    const enVal = translations.en[key];
    if (langVal === key && enVal !== key) {
      langSection[key] = enVal;
      fixedCount++;
    }
  });
});

console.log(`Fixed ${fixedCount} placeholders in non-EN sections.`);

// Write back
let output = [];
output.push('// This file is auto-generated by generate-multilang.js. Do NOT edit by hand.');
output.push('// Last updated: ' + new Date().toISOString().slice(0,16) + ' UTC');
output.push(`const translations = ${JSON.stringify(translations, null, 2)};`);
output.push(`const cityDetails = ${JSON.stringify(cityDetails, null, 2)};`);
output.push(`const carouselData = ${JSON.stringify(carouselData, null, 2)};`);
output.push('');
output.push(`module.exports = { translations, cityDetails, carouselData };`);

fs.writeFileSync(filePath, output.join('\n'));
console.log('Written back to ' + filePath);